/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

export type Param = {
  [k: string]: unknown;
} & {
  name: string;
  type: "int" | "float" | "string" | "bool" | "choice" | "color" | "entity" | "file" | "folder" | "duration";
  min?: number;
  max?: number;
  choices?: string[];
  required?: boolean;
};

/**
 * An invokable action contributed to the action registry (TRD 2B §3.1). category + destructive feed the permission model (2E §5). The engine enforces these rules in code (PROJ-161).
 */
export interface CyberDeckActionDescriptor {
  /**
   * globally-unique action id, e.g. media.volume.set
   */
  id: string;
  label: string;
  category: string;
  /**
   * contributing plugin, e.g. plugin:core.media
   */
  source?: string;
  confirmation?: boolean;
  destructive?: boolean;
  elevated?: boolean;
  params?: Param[];
}
