/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Product identity, boot manifest and API routing. Ships with the app; not editable by users or extensions (01_Architecture_Baseline.md §4). CD-108.
 */
export interface CyberDeckApplicationConfiguration {
  /**
   * document schema version; bump only with a registered migration (CD-109)
   */
  version: 1;
  identity: {
    name: string;
    /**
     * semver of the installed product
     */
    productVersion: string;
    channel: "stable" | "beta" | "dev";
  };
  boot?: {
    /**
     * ordered boot stages (BOOTSEQ()); blocking stages gate first paint
     *
     * @minItems 1
     */
    manifest: [
      {
        stage: string;
        blocking: boolean;
      },
      ...{
        stage: string;
        blocking: boolean;
      }[]
    ];
  };
  api: {
    /**
     * which ApiGateway the repositories resolve through (mock-first rule)
     */
    gateway: "mock" | "engine";
    /**
     * control-plane endpoint; required only when gateway = engine
     */
    engineUrl?: string;
  };
}
