/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * What was open when the IDE closed: workspace, selection, zoom, window bounds. Written implicitly by the session store; restored at boot stage 4 (01_Architecture_Baseline.md §4). CD-108.
 */
export interface CyberDeckSessionConfiguration {
  /**
   * document schema version; bump only with a registered migration (CD-109)
   */
  version: 1;
  activeWorkspace: string;
  /**
   * project document open in the authoring workspaces, if any
   */
  openProjectId?: string | null;
  /**
   * selected element ids in the active workspace
   */
  selection?: string[];
  zoom?: number;
  window?: {
    x?: number;
    y?: number;
    width: number;
    height: number;
    maximized?: boolean;
  };
  /**
   * ISO-8601 timestamp of the last session write
   */
  savedAt?: string;
}
