/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Keybindings: user rebinds plus extension-contributed bindings (01_Architecture_Baseline.md §4). Dispatch + rebinding store is CD-122. CD-108.
 */
export interface CyberDeckKeymapConfiguration {
  /**
   * document schema version; bump only with a registered migration (CD-109)
   */
  version: 1;
  bindings: {
    /**
     * command id from the command registry, e.g. view.commandPalette
     */
    command: string;
    /**
     * chord string, e.g. "Ctrl+K Ctrl+S"
     */
    key: string;
    /**
     * context expression gating the binding, e.g. workspace == deck-designer
     */
    when?: string;
    /**
     * who contributed the binding; user bindings shadow defaults
     */
    source?: "default" | "user" | "extension";
  }[];
}
