/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * The 7 platform feature flags — mirrors the design's FLAGDEFS() exactly (ids, defaults, semantics). User-editable for dev/experimental flags only; system flags are app-managed (01_Architecture_Baseline.md §4). CD-108.
 */
export interface CyberDeckFeatureFlags {
  /**
   * document schema version; bump only with a registered migration (CD-109)
   */
  version: 1;
  features: {
    /**
     * Experimental Widgets — unreleased manifests are discovered but hidden from Insert
     */
    expWidgets: boolean;
    /**
     * Developer Tools — Platform Inspector · boot replay · architecture markers
     */
    devTools: boolean;
    /**
     * AI Providers — pluggable completion backends behind AIService
     */
    aiProviders: boolean;
    /**
     * Marketplace — extension browsing + one-click install
     */
    marketplace: boolean;
    /**
     * Cloud Sync — workspace + project sync via SyncService
     */
    cloudSync: boolean;
    /**
     * Automation Engine — flow scheduler + background triggers
     */
    automation: boolean;
    /**
     * Plugin Sandbox — run extensions in isolated workers
     */
    pluginSandbox: boolean;
  };
}
