/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Per-workspace panel layout, sizes and presets. Edited implicitly through the UI (dragging panels), never by extensions (01_Architecture_Baseline.md §4). CD-108.
 */
export interface CyberDeckWorkspaceLayoutConfiguration {
  /**
   * document schema version; bump only with a registered migration (CD-109)
   */
  version: 1;
  /**
   * workspace this layout belongs to, e.g. deck-designer
   */
  workspaceId: string;
  panels: Panel[];
  presets?: {
    name: string;
    panels: Panel[];
  }[];
}
export interface Panel {
  id: string;
  side: "left" | "right" | "bottom" | "top";
  /**
   * panel extent in px along its docking axis
   */
  size?: number;
  visible?: boolean;
  collapsed?: boolean;
}
