/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Theme, density, active keymap and telemetry consent. Fully user-editable; extensions may not write it (01_Architecture_Baseline.md §4). CD-108.
 */
export interface CyberDeckUserPreferences {
  /**
   * document schema version; bump only with a registered migration (CD-109)
   */
  version: 1;
  theme?: {
    /**
     * active theme id
     */
    id: string;
    mode?: "dark" | "light" | "system";
  };
  density?: "comfortable" | "compact" | "spacious";
  /**
   * active keymap id; individual rebinds live in the keymap document
   */
  keymap?: string;
  /**
   * opt-in at first run (decision D4)
   */
  telemetry?: {
    enabled: boolean;
    crashReports?: boolean;
  };
}
