/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * An AI thread/completion finished. CD-114.
 */
export interface AICompletedEvent {
  threadId: string;
  status: "ok" | "failed" | "cancelled";
  /**
   * unix ms
   */
  ts?: number;
}
