/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * A device presence/heartbeat frame (engine bridge: device.paired / device.revoked + liveness). CD-114.
 */
export interface DeviceHeartbeatEvent {
  deviceId: string;
  state: "online" | "offline" | "paired" | "revoked";
  rttMs?: number;
  /**
   * unix ms
   */
  ts?: number;
}
