/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * One entry from the runtime log/event ring buffer stream. CD-114.
 */
export interface RuntimeLogEvent {
  level: "debug" | "info" | "warn" | "error";
  message: string;
  source?: string;
  /**
   * unix ms
   */
  ts?: number;
}
