/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * IDE ⇄ engine control-plane message envelope (Q4 default: WebSocket + JSON on localhost). Lineage: extends the engine transport envelope (engine/core/transport/envelope.go v/ch/type/seq/ts) with request/response correlation and subscription framing. Error payloads follow error.schema.json. CD-113.
 */
export type CyberDeckControlPlaneEnvelope = {
  [k: string]: unknown;
} & {
  /**
   * envelope version (transport.ProtocolVersion)
   */
  v: 1;
  /**
   * unique message id (uuid); response.correlation echoes it
   */
  id: string;
  /**
   * the request id this frame answers; required on response/error/event-for-subscription frames
   */
  correlation?: string;
  /**
   * frame kind
   */
  kind: "request" | "response" | "event" | "subscribe" | "unsubscribe" | "error";
  /**
   * route id (route-registry); required on request/subscribe
   */
  route?: string;
  /**
   * per-subscription monotonic sequence for gap detection + resume
   */
  seq?: number;
  /**
   * unix ms send time
   */
  ts?: number;
  /**
   * request args / response body / event data; shape is the route's request or response schema
   */
  payload?: {
    [k: string]: unknown;
  };
  error?: CyberDeckControlPlaneError;
  /**
   * subscription framing (kind=subscribe/event)
   */
  stream?: {
    /**
     * on subscribe: last seq the client already has; engine replays from seq+1 or sends a reset event if it cannot
     */
    resumeFrom?: number;
    /**
     * backpressure: max in-flight events the client will buffer; engine pauses past this until more credits arrive
     */
    credits?: number;
    /**
     * on event: true means the engine could not resume from resumeFrom — client must re-sync from this snapshot
     */
    reset?: boolean;
  };
};

/**
 * present only on kind=error
 */
export interface CyberDeckControlPlaneError {
  /**
   * stable machine code; the enum is the whole vocabulary — no free-form codes
   */
  code:
    | "bad_request"
    | "unauthorized"
    | "forbidden"
    | "not_found"
    | "conflict"
    | "validation_failed"
    | "rate_limited"
    | "unavailable"
    | "timeout"
    | "internal"
    | "not_implemented";
  /**
   * human-readable, non-localized
   */
  message: string;
  /**
   * true ⇒ the same request may succeed later (rate_limited/unavailable/timeout/internal); false ⇒ deterministic failure the client must fix (bad_request/validation_failed/not_found/…)
   */
  retryable: boolean;
  /**
   * optional structured context, e.g. field errors for validation_failed
   */
  details?: {
    [k: string]: unknown;
  };
  /**
   * hint for rate_limited/unavailable: earliest sensible retry delay
   */
  retryAfterMs?: number;
}
