/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Machine-readable registry of control-plane routes — the single source consumed by BOTH the type/client codegen (CD-115) and the MockApiGateway/EngineGateway router (CD-127). Each route names its method, request/response/event schemas, error codes and whether it streams. The route set v1 is authored against this format in CD-114. CD-113.
 */
export interface CyberDeckRouteRegistry {
  version: number;
  /**
   * @minItems 1
   */
  routes: [
    {
      [k: string]: unknown;
    },
    ...{
      [k: string]: unknown;
    }[]
  ];
}
