/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * An AI thread/completion started (flag aiProviders). CD-114.
 */
export interface AIStartedEvent {
  threadId: string;
  /**
   * unix ms
   */
  ts?: number;
}
