/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Coded error model for the control plane. `retryable` drives the middleware retry/backoff (CD-126): a client may retry retryable errors, must not retry non-retryable ones. CD-113.
 */
export interface CyberDeckControlPlaneError {
  /**
   * stable machine code; the enum is the whole vocabulary — no free-form codes
   */
  code:
    | "bad_request"
    | "unauthorized"
    | "forbidden"
    | "not_found"
    | "conflict"
    | "validation_failed"
    | "rate_limited"
    | "unavailable"
    | "timeout"
    | "internal"
    | "not_implemented";
  /**
   * human-readable, non-localized
   */
  message: string;
  /**
   * true ⇒ the same request may succeed later (rate_limited/unavailable/timeout/internal); false ⇒ deterministic failure the client must fix (bad_request/validation_failed/not_found/…)
   */
  retryable: boolean;
  /**
   * optional structured context, e.g. field errors for validation_failed
   */
  details?: {
    [k: string]: unknown;
  };
  /**
   * hint for rate_limited/unavailable: earliest sensible retry delay
   */
  retryAfterMs?: number;
}
