/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * A merged-view config value changed (matches CD-109 SettingsChanged delta shape). No engine topic. CD-114.
 */
export interface SettingsChangedEvent {
  area: string;
  path: string;
  value?: unknown;
  previous?: unknown;
  layer?: string;
  revision?: number;
}
