/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Emitted when a project document is opened (engine bridge: session.opened). CD-114.
 */
export interface ProjectOpenedEvent {
  projectId: string;
  name?: string;
  /**
   * unix ms
   */
  ts?: number;
}
