/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * IDE-internal: a widget instance was removed/unmounted. No engine topic. CD-114.
 */
export interface WidgetClosedEvent {
  widgetId: string;
  /**
   * unix ms
   */
  ts?: number;
}
