/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * A variable value changed (engine bridge: state.changed / threshold.crossed). CD-114.
 */
export interface VariableChangedEvent {
  id: string;
  value: unknown;
  previous?: unknown;
  /**
   * unix ms
   */
  ts?: number;
}
