/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * A flow run completed or failed (engine bridge: flow.run / flow.failed). CD-114.
 */
export interface FlowExecutedEvent {
  flowId: string;
  status: "ok" | "failed";
  error?: string;
  durationMs?: number;
  /**
   * unix ms
   */
  ts?: number;
}
