/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * An extension/plugin was installed/activated (engine bridge: plugin.started). CD-114.
 */
export interface ExtensionInstalledEvent {
  extensionId: string;
  version?: string;
  /**
   * unix ms
   */
  ts?: number;
}
