/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * A notification was raised (feeds the Notification Store projection). CD-114.
 */
export interface NotificationReceivedEvent {
  id: string;
  level: "info" | "warn" | "error";
  title?: string;
  body?: string;
  /**
   * unix ms
   */
  ts?: number;
}
