/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * IDE-internal: active workspace switched. No engine topic. CD-114.
 */
export interface WorkspaceChangedEvent {
  workspaceId: string;
  /**
   * unix ms
   */
  ts?: number;
}
