/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * IDE-internal: a document/file opened in an editor. No engine topic. CD-114.
 */
export interface FileOpenedEvent {
  path: string;
  /**
   * unix ms
   */
  ts?: number;
}
