/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

export type StableId = string;

/**
 * Player-facing flattened projection of a cyberdeck.project, produced engine-side at publish (Q2 default): components/variants resolved, bindings reduced to state bindings + value rules, frames snapped to the grid. Pages mirror the existing player render model (client/lib/render/model.dart) field-for-field. CD-111.
 */
export interface CyberDeckPublishedLayoutDocumentCyberdeckLayout {
  format: "cyberdeck.layout";
  /**
   * monotonic publish revision for this device (players compare to detect staleness)
   */
  version: number;
  projectId?: StableId;
  publishedAt?: string;
  device: {
    id?: StableId;
    name?: string;
    deviceClass: string;
  };
  /**
   * @minItems 1
   */
  pages: [
    {
      id: StableId;
      name?: string;
      grid?: Grid;
      version?: number;
      widgets: Widget[];
    },
    ...{
      id: StableId;
      name?: string;
      grid?: Grid;
      version?: number;
      widgets: Widget[];
    }[]
  ];
}
export interface Grid {
  columns?: number;
  rows?: number;
  gutter?: number;
  marginX?: number;
  marginY?: number;
  background?: {
    [k: string]: unknown;
  };
  deviceClass?: string;
}
export interface Widget {
  /**
   * same stable id as the authoring instance (component instances get deterministic expanded ids — see ID_AND_FLATTEN.md)
   */
  id: string;
  type: string;
  placement: Placement;
  appearance?: Appearance;
  /**
   * gesture → action ref (project events registry flattens here)
   */
  interaction?: {
    [k: string]: unknown;
  };
  config?: {
    [k: string]: unknown;
  };
}
export interface Placement {
  col: number;
  row: number;
  colSpan?: number;
  rowSpan?: number;
}
export interface Appearance {
  style?: {
    [k: string]: unknown;
  };
  /**
   * state id this widget follows (bindings with mode=variable flatten to this)
   */
  stateBinding?: string;
  /**
   * client-side value → presentation rules (expressions flatten into these where possible)
   */
  valueRules?: unknown[];
}
