/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * opaque stable id (prefix_random); NEVER derived from a display name
 */
export type StableId = string;
export type Binding = {
  [k: string]: unknown;
} & {
  mode: "static" | "variable" | "expression";
  /**
   * variable path when mode = variable
   */
  src?: string;
  /**
   * expression source when mode = expression
   */
  expr?: string;
  /**
   * literal value when mode = static
   */
  val?: {
    [k: string]: unknown;
  };
};

/**
 * Authoring truth: pages of widget instances (stable IDs — AUDIT C3), component defs/instances/overrides, binding/state/event registries, device assignments. Covers the design's serializeProject() shape plus pages/components/devices. Owned by the engine (ProjectService); see ID_AND_FLATTEN.md. CD-111.
 */
export interface CyberDeckProjectDocumentCyberdeckProject {
  format: "cyberdeck.project";
  /**
   * document schema version; the design prototype's un-schematized serialization is pre-v1 (see ID_AND_FLATTEN.md migration note)
   */
  version: 1;
  savedAt?: string;
  meta: {
    name: string;
    workspace?: string;
    createdAt?: string;
  };
  /**
   * @minItems 1
   */
  pages: [
    {
      id: StableId;
      name: string;
      /**
       * authoring canvas size in px (frames are authored against it)
       */
      canvas?: {
        w?: number;
        h?: number;
      };
      widgets: WidgetInstance[];
    },
    ...{
      id: StableId;
      name: string;
      /**
       * authoring canvas size in px (frames are authored against it)
       */
      canvas?: {
        w?: number;
        h?: number;
      };
      widgets: WidgetInstance[];
    }[]
  ];
  components?: {
    id: StableId;
    name: string;
    /**
     * prop name → default value; instances/variants override these
     */
    props?: {
      [k: string]: unknown;
    };
    /**
     * template subtree (frames relative to the component origin)
     *
     * @minItems 1
     */
    widgets: [WidgetInstance, ...WidgetInstance[]];
    variants?: {
      id: StableId;
      name: string;
      overrides?: {
        [k: string]: unknown;
      };
    }[];
  }[];
  /**
   * widget id → { prop → binding } (design registries.bindings)
   */
  bindings?: {
    /**
     * prop → binding
     */
    [k: string]: {
      [k: string]: Binding;
    };
  };
  /**
   * widget id → state definition (design registries.states)
   */
  states?: {
    [k: string]: {
      active?: string;
      custom?: string[];
      /**
       * state name → { prop → value } overrides
       */
      ov?: {
        [k: string]: {
          [k: string]: unknown;
        };
      };
    };
  };
  /**
   * widget id → { event → flow id } (design registries.events)
   */
  events?: {
    /**
     * gesture/event kind → flow id
     */
    [k: string]: {
      [k: string]: StableId;
    };
  };
  /**
   * locked widget ids (design registries.locks)
   */
  locks?: StableId[];
  /**
   * device assignments — which page each paired device renders
   */
  devices?: {
    id: StableId;
    name?: string;
    /**
     * e.g. ipad, pixel, deck
     */
    deviceClass: string;
    /**
     * opaque stable id (prefix_random); NEVER derived from a display name
     */
    pageId: string;
  }[];
  assets?: {
    id: StableId;
    kind: "image" | "icon" | "font" | "audio";
    uri: string;
  }[];
}
export interface WidgetInstance {
  id: StableId;
  /**
   * widget manifest id (widget-manifest.schema.json)
   */
  type: string;
  /**
   * display name — presentation only, never a key (AUDIT C3)
   */
  name?: string;
  frame: Frame;
  /**
   * instance settings per the manifest's configSchema
   */
  config?: {};
  locked?: boolean;
  /**
   * opaque stable id (prefix_random); NEVER derived from a display name
   */
  component?: string;
  /**
   * opaque stable id (prefix_random); NEVER derived from a display name
   */
  variant?: string;
  /**
   * prop → value overriding the component/variant defaults; requires component
   */
  overrides?: {
    [k: string]: unknown;
  };
}
export interface Frame {
  x: number;
  y: number;
  w: number;
  h: number;
}
