/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

export type NodeId = string;

/**
 * Automation graph: a trigger + typed nodes + branched edges. Maps 1:1 onto engine core/flow model.go (Flow/Trigger/Node/Edge) — see FLOW_MAPPING.md. Node kinds cover the Q3 default catalog. CD-112.
 */
export interface CyberDeckFlowDocumentCyberdeckFlow {
  /**
   * stable flow id (referenced by project events registry)
   */
  id: string;
  label: string;
  /**
   * monotonic document version (engine persists whole docs, 2D §3)
   */
  version: number;
  /**
   * whether the trigger is armed (TriggerManager.Arm); reserved schedule triggers arm but never fire in V1
   */
  armed?: boolean;
  /**
   * maps to flow.Trigger{Kind, Config}
   */
  trigger: {
    [k: string]: unknown;
  };
  /**
   * maps to []flow.Node{ID, Kind, Params}
   */
  nodes: {
    id: NodeId;
    /**
     * Q3 default catalog: Logic/Actions/Structure full; Integrations = OBS/Spotify/HTTP/MQTT; Data = Math/Text/DateTime. Validated against the flow-node registry (PROJ-161); per-kind param schemas land with CD-114 route set.
     */
    kind:
      | "logic.condition"
      | "logic.branch"
      | "logic.delay"
      | "logic.gate"
      | "action.runFlow"
      | "action.setVariable"
      | "action.setState"
      | "action.notify"
      | "action.command"
      | "structure.group"
      | "structure.comment"
      | "structure.subflow"
      | "integration.obs"
      | "integration.spotify"
      | "integration.http"
      | "integration.mqtt"
      | "data.math"
      | "data.text"
      | "data.datetime";
    /**
     * kind-specific parameters (per-kind schemas registered by the node catalog)
     */
    params?: {};
  }[];
  /**
   * maps to []flow.Edge{From, To, Label}
   */
  edges: {
    from: NodeId;
    to: NodeId;
    /**
     * branch selector — same field/name as flow.Edge.Label (json:"label"). Constrained to the true/false/always catalog; the engine accepts a superset (e.g. next)
     */
    label?: "true" | "false" | "always";
  }[];
}
