/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

export type Param = {
  [k: string]: unknown;
} & {
  name: string;
  type: "int" | "float" | "string" | "bool" | "choice" | "color" | "entity" | "file" | "folder" | "duration";
  min?: number;
  max?: number;
  choices?: string[];
  required?: boolean;
};

/**
 * A flow-node type contributed to the flow-node registry (TRD 2B §3.3). execHandle is the handle into the flow executor's execution contract (2D / PROJ-202). Enforced in code by PROJ-161.
 */
export interface CyberDeckFlowNodeDescriptor {
  /**
   * flow-node kind id, e.g. if, setVar, wait
   */
  kind: string;
  label: string;
  source?: string;
  execHandle: string;
  params?: Param[];
}
