/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

export type Param = {
  [k: string]: unknown;
} & {
  name: string;
  type: "int" | "float" | "string" | "bool" | "choice" | "color" | "entity" | "file" | "folder" | "duration";
  min?: number;
  max?: number;
  choices?: string[];
  required?: boolean;
};

/**
 * plugin.manifest.json (TRD 2F §3): a plugin's id, apiVersion, declared permissions, and registry contributions. The engine validates this, gates on apiVersion major (Master §6.4), and merges contributions into the registries (PROJ-132 enforces these rules in code).
 */
export interface CyberDeckPluginManifest {
  /**
   * reverse-DNS plugin id, e.g. com.shishir.cyberdeck.telemetry
   */
  id: string;
  name: string;
  /**
   * engine refuses an incompatible major
   */
  apiVersion: string;
  permissions?: {
    categories?: string[];
    network?: "none" | "localhost" | "outbound";
    filesystem?: "none" | "own-dir";
  };
  contributes?: {
    actions?: CyberDeckActionDescriptor[];
    widgets?: CyberDeckWidgetTypeDescriptor[];
    flowNodes?: CyberDeckFlowNodeDescriptor[];
  };
}
/**
 * An invokable action contributed to the action registry (TRD 2B §3.1). category + destructive feed the permission model (2E §5). The engine enforces these rules in code (PROJ-161).
 */
export interface CyberDeckActionDescriptor {
  /**
   * globally-unique action id, e.g. media.volume.set
   */
  id: string;
  label: string;
  category: string;
  /**
   * contributing plugin, e.g. plugin:core.media
   */
  source?: string;
  confirmation?: boolean;
  destructive?: boolean;
  elevated?: boolean;
  params?: Param[];
}
/**
 * A widget type contributed to the widget registry (TRD 2B §3.2). acceptsStateKinds lets the designer offer only compatible states when binding; gestures declares the interaction slots the type exposes. Enforced in code by PROJ-161.
 */
export interface CyberDeckWidgetTypeDescriptor {
  /**
   * widget type id, e.g. gauge.circular
   */
  type: string;
  label: string;
  source?: string;
  acceptsStateKinds?: ("scalar" | "text" | "boolean" | "enum" | "series")[];
  configSchema?: {
    name: string;
    type: string;
    default?: unknown;
  }[];
  gestures?: string[];
}
/**
 * A flow-node type contributed to the flow-node registry (TRD 2B §3.3). execHandle is the handle into the flow executor's execution contract (2D / PROJ-202). Enforced in code by PROJ-161.
 */
export interface CyberDeckFlowNodeDescriptor {
  /**
   * flow-node kind id, e.g. if, setVar, wait
   */
  kind: string;
  label: string;
  source?: string;
  execHandle: string;
  params?: Param[];
}
