/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Placeholder schema for the wire protocol envelope. Filled in by PROJ-141/PROJ-142.
 */
export interface CyberDeckProtocolEnvelope {
  [k: string]: unknown;
}
