/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

export type RouteId =
  | 'ai.threads.list'
  | 'ai.threads.suggest'
  | 'devices.assign'
  | 'devices.heartbeat'
  | 'devices.list'
  | 'devices.revoke'
  | 'flows.arm'
  | 'flows.create'
  | 'flows.delete'
  | 'flows.deploy'
  | 'flows.get'
  | 'flows.list'
  | 'flows.trace'
  | 'flows.update'
  | 'permissions.grant'
  | 'permissions.list'
  | 'permissions.revoke'
  | 'projects.create'
  | 'projects.delete'
  | 'projects.get'
  | 'projects.list'
  | 'projects.open'
  | 'projects.update'
  | 'runtime.log'
  | 'variables.get'
  | 'variables.query'
  | 'variables.subscribe'
  | 'variables.write'
  | 'widgets.manifest.get'
  | 'widgets.manifests'

export const ROUTE_IDS = [
  'ai.threads.list',
  'ai.threads.suggest',
  'devices.assign',
  'devices.heartbeat',
  'devices.list',
  'devices.revoke',
  'flows.arm',
  'flows.create',
  'flows.delete',
  'flows.deploy',
  'flows.get',
  'flows.list',
  'flows.trace',
  'flows.update',
  'permissions.grant',
  'permissions.list',
  'permissions.revoke',
  'projects.create',
  'projects.delete',
  'projects.get',
  'projects.list',
  'projects.open',
  'projects.update',
  'runtime.log',
  'variables.get',
  'variables.query',
  'variables.subscribe',
  'variables.write',
  'widgets.manifest.get',
  'widgets.manifests',
] as const
