/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Placeholder schema for typed state descriptors. Filled in by PROJ-160.
 */
export interface CyberDeckStateDescriptor {
  [k: string]: unknown;
}
