/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * Production widget manifest per 01_Architecture_Baseline.md §5 — the v2 extension of widget.schema.json (the v1 engine descriptor, kept for the live engine; see widgets/DESCRIPTOR_MAPPING.md). Widgets are discovered from these manifests, never manually imported. CD-110.
 */
export interface CyberDeckWidgetManifestV2 {
  /**
   * unique widget id, e.g. gauge.circular (v1 descriptor field: type)
   */
  id: string;
  /**
   * semver of the widget module
   */
  version: string;
  metadata: {
    label: string;
    icon?: string;
    category?: string;
    description?: string;
    tags?: string[];
  };
  /**
   * JSON Schema for instance settings (v1 descriptor used a flat name/type list)
   */
  configSchema?: {};
  /**
   * default instance config; must validate against configSchema
   */
  defaults?: {};
  /**
   * state kinds the designer may bind (same vocabulary as v1)
   */
  acceptsStateKinds?: ("scalar" | "text" | "boolean" | "enum" | "series")[];
  /**
   * interaction slots the widget exposes, e.g. tap, hold
   */
  gestures?: string[];
  /**
   * declared capabilities — enum is exactly the design's PERMS() vocabulary (§12); undeclared capabilities are denied at runtime
   */
  permissions?: (
    | "network"
    | "notifications"
    | "media"
    | "git"
    | "devices"
    | "environment"
    | "filesystem"
    | "clipboard"
    | "automation"
  )[];
  dependencies?: {
    /**
     * required platform version range, e.g. >=2.0
     */
    platform?: string;
    widgets?: string[];
  };
  dataProvider?: {
    /**
     * repository the widget reads through, e.g. variables
     */
    repo: string;
    subscribe?: boolean;
  };
  refresh?: {
    strategy: "push" | "poll" | "manual";
    /**
     * poll interval in ms; required when strategy = poll
     */
    interval?: number;
  };
  caching?: {
    policy: "none" | "swr" | "ttl";
    /**
     * seconds
     */
    ttl?: number;
  };
  lifecycle?: {
    lazy?: boolean;
    /**
     * code-split chunk name the module loads from
     */
    chunk?: string;
  };
  actions?: {
    id: string;
    label: string;
  }[];
  events?: {
    subscribes?: string[];
    emits?: string[];
  };
  /**
   * state keys persisted into the project document, keyed by stable instance id
   */
  persistedState?: string[];
}
