/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.
 * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */

/**
 * A widget type contributed to the widget registry (TRD 2B §3.2). acceptsStateKinds lets the designer offer only compatible states when binding; gestures declares the interaction slots the type exposes. Enforced in code by PROJ-161.
 */
export interface CyberDeckWidgetTypeDescriptor {
  /**
   * widget type id, e.g. gauge.circular
   */
  type: string;
  label: string;
  source?: string;
  acceptsStateKinds?: ("scalar" | "text" | "boolean" | "enum" | "series")[];
  configSchema?: {
    name: string;
    type: string;
    default?: unknown;
  }[];
  gestures?: string[];
}
