// CD-115: generate TS types from the JSON Schema contract in shared/schemas.
// One .ts per schema under ide/src/shared/contract/, plus a route-id union and
// an index barrel. The schemas are the single source of truth; these types are
// generated + CI drift-gated (regenerate → git diff --exit-code). Kernel code
// imports ONLY from @/shared/contract. Run: node scripts/gen-types.mjs
import { compileFromFile } from 'json-schema-to-typescript'
import { readFileSync, readdirSync, writeFileSync, mkdirSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, relative, basename } from 'node:path'

const schemasDir = fileURLToPath(new URL('../../shared/schemas', import.meta.url))
const outDir = fileURLToPath(new URL('../src/shared/contract', import.meta.url))

// Walk shared/schemas for *.schema.json, skipping fixtures/ and the OpenAPI export.
function findSchemas(dir) {
  const out = []
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry)
    if (statSync(p).isDirectory()) {
      if (entry === 'fixtures') continue
      out.push(...findSchemas(p))
    } else if (entry.endsWith('.schema.json')) {
      out.push(p)
    }
  }
  return out
}

// schema path → output basename: e.g. config/feature-flags.schema.json → config.feature-flags.ts
const outName = (schemaPath) =>
  relative(schemasDir, schemaPath)
    .replace(/\.schema\.json$/, '')
    .replace(/[\\/]/g, '.') + '.ts'

const bannerLines = [
  '/* AUTO-GENERATED by ide/scripts/gen-types.mjs from shared/schemas — DO NOT EDIT.',
  ' * Regenerate with `task gen:types`; CI fails if this is stale (drift gate). */',
]

// Resolve absolute $id refs (https://cyberdeck.shishir.com/schemas/…) to local
// files so codegen never touches the network.
const SCHEMA_BASE = 'https://cyberdeck.shishir.com/schemas/'
const localRefResolver = {
  order: 1,
  canRead: /^https?:\/\//i,
  read(file) {
    if (!file.url.startsWith(SCHEMA_BASE)) {
      throw new Error(`refusing to fetch external schema: ${file.url}`)
    }
    return readFileSync(join(schemasDir, file.url.slice(SCHEMA_BASE.length)), 'utf8')
  },
}

mkdirSync(outDir, { recursive: true })
const generated = []

for (const schemaPath of findSchemas(schemasDir).sort()) {
  const ts = await compileFromFile(schemaPath, {
    bannerComment: bannerLines.join('\n'),
    additionalProperties: false,
    cwd: schemasDir, // resolve $ref against the schema dir
    declareExternallyReferenced: true,
    $refOptions: { resolve: { http: localRefResolver } },
  })
  const file = outName(schemaPath)
  writeFileSync(join(outDir, file), ts)
  generated.push(file)
}

// Route-id union from the registry (used by the router + client typing).
const registry = JSON.parse(readFileSync(join(schemasDir, 'control-plane', 'routes.v1.json'), 'utf8'))
const routeIds = registry.routes.map((r) => r.id).sort()
const routeUnion =
  bannerLines.join('\n') +
  '\n\nexport type RouteId =\n' +
  routeIds.map((id) => `  | '${id}'`).join('\n') +
  '\n\nexport const ROUTE_IDS = [\n' +
  routeIds.map((id) => `  '${id}',`).join('\n') +
  '\n] as const\n'
writeFileSync(join(outDir, 'route-ids.ts'), routeUnion)
generated.push('route-ids.ts')

// Barrel. Several schemas re-declare the same shared type (e.g. StableId,
// CyberDeckControlPlaneError via $ref, or identical inline $defs), so a plain
// `export *` barrel is ambiguous (TS2308). Re-export each exported name once —
// first file wins — via explicit named re-exports.
const exportName = /^export (?:interface|type) (\w+)/gm
const seen = new Set()
const barrelLines = []
for (const file of [...generated].sort()) {
  if (file === 'route-ids.ts') continue // handled explicitly (has a runtime const)
  const src = readFileSync(join(outDir, file), 'utf8')
  const names = [...src.matchAll(exportName)].map((m) => m[1]).filter((n) => !seen.has(n))
  if (!names.length) continue
  names.forEach((n) => seen.add(n))
  barrelLines.push(`export type { ${names.join(', ')} } from './${file.replace(/\.ts$/, '')}'`)
}
writeFileSync(
  join(outDir, 'index.ts'),
  bannerLines.join('\n') +
    '\n\n' +
    barrelLines.join('\n') +
    `\nexport type { RouteId } from './route-ids'\n` +
    `export { ROUTE_IDS } from './route-ids'\n`,
)

console.log(`generated ${generated.length + 1} files in ${relative(process.cwd(), outDir)}`)
for (const f of generated) console.log('  ' + basename(f))
