// The 21 Architecture Mode notes (CD-138), transcribed from the design's ARCH()
// (Phase-4 design file). Architecture Mode renders these as markers/popovers over
// the shell. Content-only — no logic — so PM/design can edit without touching code.

export interface ArchNote {
  id: string
  title: string
  what: string
  how: string
  why: string
}

export const ARCH_NOTES: ArchNote[] = [
  { id: 'boot', title: 'Boot Manager', what: 'Owns the startup lifecycle: config → auth → workspace restore → theme → service container → command registry → extension host → widget registry → background services.', how: 'Runs an ordered list of boot contributions; only shell-critical phases block first paint.', why: 'The shell is usable in ~140 ms even while widget discovery, extensions and indexers keep loading.' },
  { id: 'config', title: 'Configuration Loader', what: 'Layered configuration: defaults ← application ← user ← workspace ← runtime overrides.', how: 'Each layer is a document; ConfigurationService merges them and emits SettingsChanged deltas.', why: 'Nothing is hardcoded — features, layouts, keymaps and widgets are all configuration.' },
  { id: 'wsmgr', title: 'Workspace Manager', what: 'Routes between the seven workspaces and owns per-workspace layout state.', how: 'setWorkspace() mutates AppState and notifies subscribers; panes subscribe rather than being shown imperatively.', why: 'Rail, breadcrumb, status bar and panes stay decoupled — adding a workspace is a config entry.' },
  { id: 'cmdreg', title: 'Command Registry', what: 'Every action in the app is a command: palette, shortcuts, toolbar, menus and buttons resolve through one registry.', how: 'Entries carry id, category, keybinding, visibility context and undo support.', why: 'One execution path means telemetry, permissions, undo and rebinding come for free.' },
  { id: 'svc', title: 'Service Container', what: 'A DI container holding ~13 platform services resolved by interface.', how: 'Services register at boot as lazy proxies and are resolved by interface, never imported directly.', why: 'DI lets services be mocked, swapped (mock API → real API) and lazy-loaded.' },
  { id: 'widgetreg', title: 'Widget Registry', what: 'Widgets are self-contained modules discovered from manifests — never manually imported.', how: 'Discovery → dependency resolution → registration → lazy initialization → render.', why: 'New widgets appear without changing core code; the registry is the single source of truth.' },
  { id: 'dock', title: 'Dock & Layout Manager', what: 'Tool windows are managed dock items — float, pin, auto-hide, peek — not ad-hoc divs.', how: 'DockManager owns per-window state {mode, side, size, pinned}; persists in the layout store.', why: 'Centralizing tool-window semantics makes every future panel dockable for free.' },
  { id: 'layout', title: 'Layout Presets', what: 'Named layout configurations per workspace (Balanced, Focus, Docked Tools + user-saved).', how: 'A preset is pure configuration; applying one writes the workspace layout store.', why: 'The shell renders whatever the layout config says — it owns nothing itself.' },
  { id: 'theme', title: 'Theme Engine', what: 'Design tokens resolved from theme configuration and applied before first paint.', how: 'ThemeService writes CSS custom properties at boot stage 5, then emits ThemeChanged.', why: 'Token-based theming means extensions contribute themes and every widget inherits them.' },
  { id: 'exthost', title: 'Extension Host', what: 'Plugins run in an isolated extension host and contribute widgets, commands, variables, nodes, menus and themes.', how: 'Each extension declares contribution points; the host activates them lazily through permissioned APIs.', why: 'The core never changes when extensions are added — a crash cannot take down the shell.' },
  { id: 'notif', title: 'Notification Service', what: 'Central sink for toasts, drawer items and badges — any service can notify without owning UI.', how: 'notify({priority, source, actions}) → queued, deduped, rate-limited; the drawer is a projection.', why: 'Decouples producers from presentation; enables do-not-disturb and per-source muting.' },
  { id: 'telemetry', title: 'Telemetry & Sessions', what: 'Batched, non-blocking observability plus collaborative session presence.', how: 'TelemetryService buffers events in memory and flushes in the background, never on the UI thread.', why: 'A production IDE is tuned from real usage data; batching keeps it invisible.' },
  { id: 'eventbus', title: 'Event Bus', what: 'Application-wide pub/sub; widgets and services never call each other directly.', how: 'Typed events with payload schemas; subscribers receive events async.', why: 'Full decoupling — a gauge re-renders on VariableChanged without knowing the producer.' },
  { id: 'repo', title: 'Repository Layer', what: 'The UI never touches JSON directly: Widget → Repository → Service → Gateway → DB → Configuration.', how: 'Repos expose query(scope, filter, sort, page); middleware adds latency, retries, caching, cancellation.', why: 'When the real backend arrives, only the gateway swaps — everything else keeps working.' },
  { id: 'stores', title: 'State Stores', what: 'No god-store: domain stores each declare persisted / temp / derived / cached / server-backed.', how: 'Stores are subscribed projections; persisted ones write behind and restore at a declared boot timing.', why: 'Domain boundaries keep invalidation precise and restarts predictable.' },
  { id: 'mockapi', title: 'Mock API Gateway', what: 'A simulated REST gateway with latency distributions, pagination, auth, failures and retries.', how: 'Intercepts repository requests, resolves from the mock DB, injects 15–200 ms latency + 2% failures.', why: 'The UI is forced to handle loading/empty/error/retry now — real integration is a config change.' },
  { id: 'jobs', title: 'Background Services', what: 'Work that never blocks interaction: telemetry flush, health checks, indexing, watchers, cache refresh.', how: 'A job scheduler runs tasks on idle callbacks / workers with budgets and backoff.', why: 'Production apps feel fast because nothing periodic runs on the interaction path.' },
  { id: 'cache', title: 'Cache Manager', what: 'Browsers render from cached repository reads — thumbnails and manifests are not re-fetched per open.', how: 'LRU + persisted cache with event-driven invalidation: an event evicts exactly the affected entries.', why: 'Repeat navigation is free; precise invalidation keeps caches trustworthy.' },
  { id: 'ai', title: 'AI & Automation Platform', what: 'AI features and automation nodes are platform services, not widgets; providers are pluggable.', how: 'AIService routes to the configured provider; flow nodes call it like any action node.', why: 'Isolating providers behind a service keeps flows and UI stable while backends swap.' },
  { id: 'plugin', title: 'Plugin Host — Devices', what: 'Device connectivity is a device plugin family running in the plugin host with declared permissions.', how: 'Each driver declares {network, devices} permissions; heartbeats arrive as events.', why: 'New hardware means a new plugin, not a core change — a misbehaving driver is sandboxed.' },
  { id: 'projrepo', title: 'Project Service & Repository', what: 'The project table renders from ProjectRepository, not a hardcoded array.', how: 'ProjectService loads the serialized ProjectModel doc, hydrates registries, emits ProjectOpened.', why: 'The service boundary makes save/load/sync/collaboration one implementation site.' },
]
